// Mocks generated by Mockito 5.4.6 from annotations
// in daggerheart_beyond/test/data/auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:daggerheart_beyond/data/data_sources/firebase_auth_data_source.dart'
    as _i3;
import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseAuth_0 extends _i1.SmartFake implements _i2.FirebaseAuth {
  _FakeFirebaseAuth_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserCredential_1 extends _i1.SmartFake
    implements _i2.UserCredential {
  _FakeUserCredential_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FirebaseAuthDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseAuthDataSource extends _i1.Mock
    implements _i3.FirebaseAuthDataSource {
  MockFirebaseAuthDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseAuth get firebase =>
      (super.noSuchMethod(
            Invocation.getter(#firebase),
            returnValue: _FakeFirebaseAuth_0(
              this,
              Invocation.getter(#firebase),
            ),
          )
          as _i2.FirebaseAuth);

  @override
  set firebase(_i2.FirebaseAuth? _firebase) => super.noSuchMethod(
    Invocation.setter(#firebase, _firebase),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i2.UserCredential> createAccount({
    required String? email,
    required String? password,
    required String? username,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createAccount, [], {
              #email: email,
              #password: password,
              #username: username,
            }),
            returnValue: _i4.Future<_i2.UserCredential>.value(
              _FakeUserCredential_1(
                this,
                Invocation.method(#createAccount, [], {
                  #email: email,
                  #password: password,
                  #username: username,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.UserCredential>);

  @override
  _i4.Future<_i2.UserCredential> logIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#logIn, [], {#email: email, #password: password}),
            returnValue: _i4.Future<_i2.UserCredential>.value(
              _FakeUserCredential_1(
                this,
                Invocation.method(#logIn, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.UserCredential>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> resetPasswordFromCurrentPassword({
    required String? currentPassword,
    required String? newPassword,
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPasswordFromCurrentPassword, [], {
              #currentPassword: currentPassword,
              #newPassword: newPassword,
              #email: email,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAccount({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
